Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/04/2022
Var
// Seção de Declarações das variáveis
I,M: REAL

Inicio
ESCREVA("DIGITE O NUMERO PARA FATORAR: ")
LEIA(I)
M <- 1
ENQUANTO (I>=1) FACA
M <- M*I
I <- I-1
ESCREVAL(M)
FIMENQUANTO


Fimalgoritmo