Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/04/2022
Var
// Seção de Declarações das variáveis 
C,M: INTEIRO

Inicio
PARA C DE 0 ATÉ 9999 FACA
C <- M
M <- M+C
ESCREVAL(M)
FIMPARA
Fimalgoritmo