Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/04/2022
Var
// Seção de Declarações das variáveis 
N: INTEIRO

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
ENQUANTO (N<5) FACA
N <- N+1
ESCREVAL(N)
FIMENQUANTO

Fimalgoritmo