Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/04/2022
Var
// Seção de Declarações das variáveis 
C,TAB: INTEIRO

Inicio
ESCREVAL("DIGITE A TABUADA: ")
LEIA(TAB)
PARA C DE 1 ATÉ 10 FACA
ESCREVAL(TAB*C)
FIMPARA
Fimalgoritmo