Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/05/2022
Var
// Seção de Declarações das variáveis 
N1, N2: REAL

Inicio
ESCREVAL("DIGITE NÚMERO 01")
LEIA(N1)
ESCREVAL("DIGITE NÚMERO 02")
LEIA(N2)
SE (N1-N2 < 0) ENTAO
ESCREVAL((N1-N2)*-1)
SENAO
ESCREVAL(N1-N2)
FIMSE

Fimalgoritmo