algoritmo "semnome"
// Função :
// Autor :
// Data : 14/03/2022
// Seção de Declarações 
var
n1,n2,n3,n4: REAL
inicio
ESCREVA("DIGITE N1 DE PESO 1:",n1)
LEIA(N1)
ESCREVA("DIGITE N2 DE PESO 2:",n2)
LEIA(N2)
ESCREVA("DIGITE N3 DE PESO 3:",n3)
LEIA(N3)
ESCREVA("DIGITE N4 DE PESO 4:",n3)
LEIA(N4)

ESCREVAL("")
ESCREVAL("MÉDIA PONDERADA",((n1*1)+(n2*2)+(n3*3)+(n4*4))/4)
fimalgoritmo
