Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/04/2022
Var
// Seção de Declarações das variáveis 
I,N: INTEIRO

Inicio
I <- 0
ENQUANTO (I < 9) FACA
I<- I+1
N<- I*2
ESCREVAL(I:4,N:12)
//ESCREVA(N:2)
FIMENQUANTO

Fimalgoritmo